name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  release:
    types: created
  workflow_dispatch:

jobs:
  build:
    name: Build Ghidra extension
    strategy:
      fail-fast: false
      matrix:
        ghidra-version:
          - '10.0.4'
    runs-on: ubuntu-latest
    container: registry.gitlab.com/torgo/ghidra-container/ghidra-plugin-builder:${{ matrix.ghidra-version }}
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Compile - ${{ matrix.ghidra-version }}
        run: |
          gradle
          ls -lah dist/
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

